version: "3.9"

services:
  samuca-mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - samuca-network

  samuca-api:
    build: .
    command: ["/wait-for-it.sh", "samuca-mysql:3306", "-t", "30" ,"--", "java", "-jar", "api.jar"]
    image: samuca-api
    environment:
      DB_HOST: samuca-mysql
    networks:
      - samuca-network
    depends_on:
      - samuca-mysql

  samuca-nginx:
    build: ./nginx
    image: samuca-nginx
    ports:
      - "80:80"
    networks:
      - samuca-network
    depends_on:
      - samuca-api

networks:
  samuca-network:
    driver: bridge
